### ISSUE TITLE
How can I handle on scroll event?

### ISSUE THREAD

**Issue by dipongkor** [echa/ng-scrollable#19]
I need to load more data while scrolling to the bottom. Please guide me how can I do that?

**Comment by echa** [comment]
Here's how you can achieve infinite scrolling. Note that this solution does not limit the number of DOM nodes nor scopes or watchers inside the scrollable container. The more content you load the more memory gets used. ng-scrollable does also not consider the size or layout of individual content blocks. It's entirely up to you to calculate when and how much extra content you fetch. 

First you listen to the **scrollable.dimensions** event in your controller.
```
$scope.$on('scrollable.dimensions', updateDimensions);
```
The event gets fired whenever dimensions of either the container or the content change. 

Second, you set a **scroll spy** on the directive in your template. You need to use an expression that  evaluates to a settable variable or otherwise ng-scrollable will not write to it (the example assumes you export your controller under the name `ctrl` to the scope (using the `controller as` syntax):
```
<div scrollable data-spy-y="ctrl.spy"></div>
```

Third, you **watch** the spy variable in your controller and call your own update function on change
```
$scope.$watch('ctrl.scrollSpy', scrollUpdate);
```

**Comment by dipongkor** [comment]
I have implemented third one already. Anyway, thanks much for you response 

$scope.$watch('ctrl.scrollSpy', scrollUpdate);
