### ISSUE TITLE
Doesn't display all items

### ISSUE THREAD

**Issue by yahyaKacem** [echa/ng-scrollable#35]
hey, I'm trying this plugin with AngularJS 1.4.7 or 1.5.0-rc.0 but it seems like it sometimes displays the wrong number of items, some stay out of view, [plunker v1.4.7](http://plnkr.co/edit/sW03QZ13pV4A7lbnxKnP?p=preview), [v1.5.0-rc.0](http://plnkr.co/edit/pBuawEG0jYcYoEI1Clf0?p=preview).
For 100 user I get sometimes 99 [0-98], sometimes 69 [0-68], and sometimes I got the whole 100 [0-99].

**Comment by echa** [comment]
The problem here is that the **size of your images is unkown** to the browser's layout engine at the time ng-scrollable refreshes the content's dimensions. Here is what happens in order:

1. at startup ng-scrollable starts with empty content (ng-repeat generates no DOM nodes)
2. during the $digest cycle right after setUsers() is called in your promise chain ng-repeat renders DOM nodes for all users (these are full nodes including the <img> node, but lacking an image file width and height are zero)
3. ng-scrollable's MutationObserver sees the DOM update and refreshes dimensions (using the current layout where images are 0x0)
4. the browser asynchronously loads images and updates the layout multiple times as images become available

The problem here comes from point 4. There is no 'layout changed' event, so ng-scrollable cannot update dimensions.

Here are two possible solutions:

1. set a fixed width and height for your images, or in general, all repeating content you put inside ng-scrollable
2. call `$scope.$broadcast('content.changed')` from your controller after layout changes

Solution 2 is tricky in your case, but can be accomplished when you load images in Javascript in addition to ng-src so you can wait for completion like:
```
$q.all(app.users.map(function (u) {
  var img = new Image;
  var d = $q.defer();
  img.onload = function () { d.resolve(); };
  img.onerror = function () { d.resolve(); };
  img.url = u.picture;
  return d.promise;
}))
.then(function () { 
  $scope.$broadcast('content.changed'); 
});
```

**Comment by yahyaKacem** [comment]
:+1:
