### ISSUE TITLE
displacement speed more speed

### ISSUE THREAD

**Issue by negronigro** [echa/ng-scrollable#43]
how do more faster the velocity scrollbar horizontal when moving with the mouse?

**Comment by echa** [comment]
I'm not sure I understand your question. To influence scroll speed there is two undocumented options you can try playing with: `wheelSpeed` (integer, default = 1) and `kineticTau` (integer, default = 325).

The first option is a multiplier for wheel event's delta value. Keep in mind that this is normalized across browsers since the latest ngScrollable version. That means with FF/Chrome on Windows you already get long jumps since the wheel resolution is not as fine-grained as on OSX for example.

The `kineticTau` option influences the duration of the kinetic scroll on touch-based devices. Higher values make the scrollable content seem more heavy when moved with a finger. For more info read http://ariya.ofilabs.com/2013/08/javascript-kinetic-scrolling-part-1.html

**Comment by echa** [comment]
closing for age
