### ISSUE TITLE
Does this library support using text as scrollable content?

### ISSUE THREAD

**Issue by kilik52** [echa/ng-scrollable#51]
I'm trying to add a horizontal text menu using this library, but failed. 
Does this library support using text as scrollable content?

**Comment by echa** [comment]
Yes, it supports everything you can put inside a DOM node, including text. If scrollbars do not show up after initialization, you may need to send an explicit `content.changed` event (see the main README.md for details).

TL;TR

ngScrollable needs to know the content's width and height in order to display and update scrollbars. It usually re-reads the actual size from the DOM after changes to the DOM tree inside the scrollable content happen, when the browser is resized or when you send a `content.changed` event. 

Sometimes ngScrollable is too fast and reads the size before the browser renders any CSS styles. This may happen during initialization, but also when you change CSS or style attributes on elements. Note that adding or removing DOM nodes (e.g. using ngRepeat) is detected, so ngScrollable updates size correctly.
