### ISSUE TITLE
Scroll event broadcast feature suggestion

### ISSUE THREAD

**Issue by enchained** [echa/ng-scrollable#52]
I'd like to use the same transform with transition on some element, so I could move it synchronously with the scrollable element. Could you please add a scroll event broadcast, with scroll coordinates and maybe styles, so I could apply transform and transition to another element?

**Comment by echa** [comment]
Have you tried `spyX` and `spyX` attributes already? They are there for your special use case. Angular events would be a performance killer for almost any app since they are fired way too often during scroll.

Have a look at the 3rd example on http://echa.github.io/ng-scrollable/ - note X and Y positions under the image are updated when you scroll. That's essentially the values you can use in your own CSS transform.

**Comment by enchained** [comment]
Yes, I tried $watch-ing spyX attribute, but there's too much visible lag, which is bad in my case - I need to   horizontally scroll/transform table header, that is separate from (two ways scrollable) table body, simultaneously with the body. On the second thought, I should try to rearrange things by giving a horizontal scroll to the whole table container instead of body and that might solve the problem.

**Comment by echa** [comment]
closing this for age
