### ISSUE TITLE
How to write a scroll event?

### ISSUE THREAD

**Issue by jeni27** [echa/ng-scrollable#53]
I need to call a function in scroll event. How to do it?. Plz reply this issue ASAP...

**Comment by echa** [comment]
Hi Jenifer,

events are really bad in Angular because they kill your performance. For scroll events it's even worse because hundreds can get fired per second. That's the reason something else exists in ng-scrollable: scroll spies. Have a look at `spyX` and `spyY` in the docs and the 3rd demo on the demo page. You can use a controller- or scope-bound function as a spy. If you still need events, emit one in this function.
