### ISSUE TITLE
not getting scrollbar if I have ng-show

### ISSUE THREAD

**Issue by Kamesh312** [echa/ng-scrollable#60]
Hi,
  I am not getting scrollbar if I have ng-show in my ul element. If i remove this its fine. Can you please help me as I m stucked here. Here is my ul element
<ul class="ct-scroll" ng-scrollable="{scrollX:'none',scrollY:'right'}" ng-show="showAllPriors" spy-y="posY">

**Comment by Kamesh312** [comment]
Hi,
  I am not getting scrollbar if I have ng-show in my ul element. If i remove this its fine. Can you please help me as I m stucked here. Here is my ul element
<ul class="ct-scroll" ng-scrollable="{scrollX:'none',scrollY:'right'}" ng-show="showAllPriors" spy-y="posY">

**Comment by echa** [comment]
There are no DOM events triggered for visibility changes, so ng-scrollable does not update automatically when ng-show adds or removes its CSS classes to your ul element. It's a conceptual limit of the DOM, nothing I can fix here. That means you cannot use ng-show/ng-hide without additional effort.

You may use ng-if instead of ng-show, but that generates an extra scope which you may not want. Another option is to explicitly send a `content.changed` event from your controller every time your ng-show condition changes.
