### ISSUE TITLE
scrollable.scroll.bottom on a specific scroll

### ISSUE THREAD

**Issue by Maethorin** [echa/ng-scrollable#67]
Hi echa!

ng-scrollable is really a nice work! gratz!

I have a page with several panels and each one with a `ng-scrollable` on a list of things. I need a button to add new thing and want this list to `scroll.bottom` so the new field will become visible for the user.

How can I `$scope.$broadcast('scrollable.scroll.bottom');` only in a specific panel? I can pass scroll options for each `ng-scrollable`and I'm setting an `id` for each one.

tys!
[]s

**Comment by echa** [comment]
Hi Márcio! Thanks!

Doing this via broadcast actually requires me to extend ng-scrollable because incoming events are not filtered by id.

There's another way for you to achieve the desired result. You can emit a `focus` event on new DOM elements right after adding them (preferably doing this async). ng-scrollabe listens to focus events and auto-scrolls the source of the event into view. The only thing you need to remember is that the element has to be rendered already (it's real CSS size must be known). Although that's a bit hacky, you may defer sending the focus event until after rendering using `scope.$applyAsync()`. Have a look at #66 for inspiration.

**Comment by Maethorin** [comment]
Excelent! Do you think I can use `ng-focus` for this or a custom directive with a little `$timeout` before set the focus to the element? I was already thinking in doing something like this anyway.

**Comment by echa** [comment]
No, `ng-focus` captures the focus event for you and executes an expression. It works similar to `ng-click`. What you need is the other way around. You want to **trigger** the focus event at a DOM element of your choice. See my comments to #66

**Comment by Maethorin** [comment]
Its works nicely!

I was thinking something like this, but I was using a `$timeout` to hold `element[0].focus();` but with `scope.$applyAsync` seems to be the "right way".

Thank You Alexander!

**Comment by jakett** [comment]
You can use animate function. Example: 
`function linkFn(scope, element, attrs) {
     var el = $(element);
     var scrollElement = el.find('.console-log-container .scrollable');

     scope.watchCollection(function() { return UtilFactory.getLogs(); }, watchLogs);

     function watchLogs(newValue, oldValue) {
          scrollElement.animate({scrollTop: 20}, 10);
     }
}`
Good luck!
